config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  root 'posts#index'

  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  before_create :set_comment_number
  has_rich_text :body

  #Setting polymorphic comments
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  private

  def set_comment_number
    self.comment_number = user.comment_created
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy
  # active storage from Rails 5 #
  has_one_attached :thumbnail
  has_one_attached :banner
  # action text from Rails 6 #
  has_rich_text :body

  validates :title, length: { minimum: 5 }
  validates :body,  length: { minimum: 25 }

  # self.per_page = 10

  # extend FriendlyId
  # friendly_id :title, use: :slugged

  def optimized_image(image,x,y)
    return image.variant(resize_to_fill: [x,y]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy

  def username
    return email.split("@")[0].capitalize
  end


  def comment_created
    #This is the same thing as num_comments +=1
    self.number_of_comments = number_of_comments + 1
    save
    number_of_comments
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin!

  private

  def is_admin!
    if current_user && current_user.admin
      #then do nothing - only admin can post to this blog
    else
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: [:create]
  before_action :set_comment, except: [:create]
  before_action :authenticate_user!

  def create
    #creating new child object for commentable
    @comment = @commentable.comments.build(comment_params)
    #we can assign to current_user as we authenticate above: before_action :authenticate_user!
    @comment.user = current_user
    @comment.reply = true if params[:comment_id]
    @comment.save
  end

  def edit
  end

  def update
    if @comment.edit_history == ""
      #body - comment model has_rich_text :body
      @comment.edit_history = "Original " + @comment.body.body.to_plain_text + "\n"
    else
      @comment.edit_history = @comment.edit_history + "Edit: " + params[:comment][:body] + "\n"
    end
  @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  def history
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    #comment - commenting on the comment
    if params[:comment_id]
      #commentable used ony inside create action
      @commentable = Comment.find_by_id(params[:comment_id])
    elsif params[:post_id]
      @commentable = Post.find_by_id(params[:post_id])
    end
    #post - commenting on the post
  end

  def set_comment
    @comment = comment.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  #added after scaffold was generated:
  before_action :authenticate_user!, except: [:index, :show]

  #is_admin method from application controller
  before_action :is_admin!, except: [:index, :show]

  POSTS_PER_PAGE = 10

  # GET /posts or /posts.json
  def index
    #params are strings => array, to_i to convert it to integer
    @page = params.fetch(:page, 0).to_i
    @all_posts = Post.all.order("created_at DESC")
    @number_of_pages = @all_posts.length/POSTS_PER_PAGE
    @posts = @all_posts.offset(@page * POSTS_PER_PAGE).limit(POSTS_PER_PAGE)
    # .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /posts/1 or /posts/1.json
  def show
    views = @post.views
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    #added after scaffold was generated:
    #post belongs to user
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">My Blog</a>
    <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- ###left section of nabar### -->
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:'nav-link' %>
        <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class:'nav-link' %>
        <!-- <a class="nav-link" href="#">Link</a> -->
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <!-- ###right section of navbar### -->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
           <!--  ###users set to be admin### -->
            <% if current_user.admin %>
            <!-- <a class="dropdown-item" href="#">New Post</a> -->
            <%= link_to "New Post", new_post_path, class:'dropdown-item' %>
            <% end %>
            <%= link_to "Account Setting", edit_user_registration_path, class:'dropdown-item'%>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign-in", new_user_session_path, class:'nav-link' %>
          <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">About Me</h1>
      <div class="row">
        <p style="text-align: justify">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit earum adipisci autem sequi, at excepturi reiciendis, vitae optio enim possimus dolorem ipsa minus molestiae consequatur, explicabo, voluptatum? Perspiciatis, enim, repudiandae?
          <br>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo iure facere amet corrupti quae impedit consequatur dignissimos officia laborum, quidem itaque in dolore tempore repudiandae eligendi exercitationem excepturi quam distinctio?
          <br>
          Lorem ipsum, dolor sit amet, consectetur adipisicing elit. Voluptates omnis, eaque cumque, reiciendis voluptas beatae, repellat aliquam earum officia, ipsum recusandae obcaecati commodi ea accusantium quas illo ab consectetur a.
        </p>
        <hr class="my-4">
     </div>
      <button type="button" class="btn btn-outline-primary" onclick="window.location.href = 'https://instagram.com';">Instagram</button>
      <button type="button" class="btn btn-outline-secondary" onclick="window.location.href = 'https://twitter.com';">Twitter</button>
      <button type="button" class="btn btn-outline-success" onclick="window.location.href = 'https://youtube.com';">YouTube</button>
  </div>
</div>



<div class="about">
  <div class="about-inner">

  </div>
</div>

app/views/posts/_form.html.erb
<div class="form">
<%= form_with model: post do |f| %>

  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>
    <%= f.label :thumbnail, class:'form-control' %>
    <%= f.file_field :thumbnail %>
    <%= f.label :banner, class:'form-control' %>
    <%= f.file_field :banner %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">

    <div class="row">
        <div class="digg_pagination">
            <%#= will_paginate @posts, :container => false %>
            <%= link_to "Previous Page", posts_path(page: @page - 1) %>
            <% for page_number in 1..@number_of_pages do %>
              <%= link_to page_number, posts_path(page: page_number-1) %>
            <% end %>
            <%= link_to "Next Page", posts_path(page: @page + 1) %>
        </div>
    </div>

    <% @posts.each do |post| %>
    <div class="row">
        <div class="card mb-3">
            <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card" />
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to post.title, post %>
                </h5>
                <p class="card-text">
                    <%= post.body.to_plain_text.truncate_words(50) %>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
                        <%= post.user.username %> | <%= pluralize(post.views, "View") %> | 0 comments
                    </small>
                </p>
            </div>
        </div>
    </div>
    <% end %>
</div>


<div class="post-index-main">
  <div class="post-index-inner-top">
    <% @posts.each do |post| %>
     <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card" />
        <div class="post-index-body">
          <h5><%= link_to post.title, post %></h5>
          <p><%= post.body.to_plain_text.truncate_words(50) %></p>
        </div>
  </div>
  <div class="post-index-inner-bottom">
    <div class="post-index-details">
      <p><%= post.updated_at.strftime("%A, %B %e, %Y") %> by</p>
      <p> <%= post.user.username %> | <%= pluralize(post.views, "View") %> | 0 comments</p>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
  <%= image_tag(@post.banner, style:'width:100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>